<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fitradar.Domain\Fitradar.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\" />
    <Folder Include="Dao\" />
    <Folder Include="ReadStore\" />
  </ItemGroup>

</Project>
